name: reviews_dw
version: "1.0.0"
config-version: 2

profile: reviews_dw

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  reviews_dw:
    staging:
      +materialized: view
    marts:
      +materialized: table
